baseURL = "https://hack-mas.at"
title = "Håck ma's!"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
[languages]

  [languages.de]
    languageName = "Deutsch"
    weight = 1

  [languages.en]
    languageName = "English"
    weight = 2
