baseURL = "https://hack-mas.at"
title = "Håck ma's!"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false

theme = "PaperMod"
enableRobotsTXT = true

[params]
  defaultTheme = "dark"
  disableThemeToggle = true
  mainSections = ["posts"]
  ShowRelatedContent = false
  ShowPostNavLinks = false
  author = "Håck ma's Orga"
  email = "kontakt@hack-mas.at"

[params.label]
  text = ""
  icon = "/images/kraken.svg"
  iconHeight = 50

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1

  [languages.en]
    languageName = "English"
    weight = 2

[[languages.de.menu.main]]
name = "FAQ" 
url = "/faq/"
weight = 2

[[languages.de.menu.main]]
name = "Tickets"
url = "/tickets/"
weight = 3

[[languages.de.menu.main]]
name = "Kontakt"
url = "/contact/"
weight = 5

[[languages.de.menu.side]]
name = "Home"
url = "/"
weight = 1

[[languages.de.menu.side]]
name = "Code of Conduct"
url = "/codeofconduct/"
weight = 2

[[languages.de.menu.side]]
name = "Accessibility"
url = "/accessibility/"
weight = 3

[[languages.de.menu.side]]
name = "Tickets"
url = "/tickets/"
weight = 4

[[languages.de.menu.side]]
name = "Mitmachen & Mitbringen"
url = "/mitmachen/"
weight = 5

[[languages.de.menu.side]]
name = "Anreise"
url = "/anreise/"
weight = 6

[[languages.de.menu.side]]
name = "Übernachtung"
url = "/uebernachtung/"
weight = 7

[[languages.de.menu.side]]
name = "FAQ"
url = "/faq/"
weight = 8


[[languages.en.menu.main]]
name = "FAQ"
url = "/en/faq/"
weight = 2

[[languages.en.menu.main]]
name = "Tickets"
url = "/en/tickets/"
weight = 3

[[languages.en.menu.main]]
name = "Contact"
url = "/en/contact/"
weight = 5

[[languages.en.menu.side]]
name = "Home"
url = "/en/"
weight = 1

[[languages.en.menu.side]]
name = "Code of Conduct"
url = "/en/codeofconduct/"
weight = 2

[[languages.en.menu.side]]
name = "Accessibility"
url = "/en/accessibility/"
weight = 3

[[languages.en.menu.side]]
name = "Tickets"
url = "/en/tickets/"
weight = 4

[[languages.en.menu.side]]
name = "Participate"
url = "/en/mitmachen/"
weight = 5

[[languages.en.menu.side]]
name = "Arrival"
url = "/en/anreise/"
weight = 6

[[languages.en.menu.side]]
name = "Overnight Stay"
url = "/en/uebernachtung/"
weight = 7

[[languages.en.menu.side]]
name = "FAQ"
url = "/en/faq/"
weight = 8
